CREATE TABLE chats (
    id UUID PRIMARY KEY
);

CREATE TABLE messages (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    chat_id UUID NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
